INSERT INTO `countries` (`code`, `name`, `dial_code`, `currency_name`, `currency_symbol`, `currency_code`) VALUES
( 'DZ', 'Algeria', 213, 'Algerian dinar', 'د.ج', 'DZD'),
( 'AO', 'Angola', 244, 'Angolan kwanza', 'Kz', 'AOA'),
( 'AR', 'Argentina', 54, 'Argentine peso', '$', 'ARS'),
( 'AU', 'Australia', 61, 'Australian dollar', '$', 'AUD'),
( 'AT', 'Austria', 43, 'Euro', '€', 'EUR'),
( 'BH', 'Bahrain', 973, 'Bahraini dinar', '.د.ب', 'BHD'),
( 'BD', 'Bangladesh', 880, 'Bangladeshi taka', '৳', 'BDT'),
( 'BY', 'Belarus', 375, 'Belarusian ruble', 'Br', 'BYN'),
( 'BE', 'Belgium', 32, 'Euro', '€', 'EUR'),
( 'BR', 'Brazil', 55, 'Brazilian real', 'R$', 'BRL'),
( 'KH', 'Cambodia', 855, 'Cambodian riel', '៛', 'KHR'),
( 'CM', 'Cameroon', 237, 'Central African CFA ', 'Fr', 'XAF'),
( 'CA', 'Canada', 1, 'Canadian dollar', '$', 'CAD'),
( 'CL', 'Chile', 56, 'Chilean peso', '$', 'CLP'),
( 'CO', 'Colombia', 57, 'Colombian peso', '$', 'COP'),
( 'CR', 'Costa Rica', 506, 'Costa Rican colón', '₡', 'CRC'),
( 'CZ', 'Czech Republic', 420, 'Czech koruna', 'Kč', 'CZK'),
( 'DK', 'Denmark', 45, 'Danish krone', 'kr', 'DKK'),
( 'DO', 'Dominican Republic', 1809, 'Dominican peso', '$', 'DOP'),
( 'EC', 'Ecuador', 593, 'United States dollar', '$', 'USD'),
( 'EG', 'Egypt', 20, 'Egyptian pound', '£ or ج.م', 'EGP'),
( 'SV', 'El Salvador', 503, 'United States dollar', '$', 'USD'),
( 'ET', 'Ethiopia', 251, 'Ethiopian birr', 'Br', 'ETB'),
( 'FI', 'Finland', 358, 'Euro', '€', 'EUR'),
( 'FR', 'France', 33, 'Euro', '€', 'EUR'),
( 'GE', 'Georgia', 995, 'Georgian lari', 'ლ', 'GEL'),
( 'DE', 'Germany', 49, 'Euro', '€', 'EUR'),
( 'GH', 'Ghana', 233, 'Ghana cedi', '₵', 'GHS'),
( 'GR', 'Greece', 30, 'Euro', '€', 'EUR'),
( 'GT', 'Guatemala', 502, 'Guatemalan quetzal', 'Q', 'GTQ'),
( 'HU', 'Hungary', 36, 'Hungarian forint', 'Ft', 'HUF'),
( 'IN', 'India', 91, 'Indian rupee', '₹', 'INR'),
( 'ID', 'Indonesia', 62, 'Indonesian rupiah', 'Rp', 'IDR'),
( 'IE', 'Ireland', 353, 'Euro', '€', 'EUR'),
( 'IL', 'Israel', 972, 'Israeli new shekel', '₪', 'ILS'),
( 'IT', 'Italy', 39, 'Euro', '€', 'EUR'),
( 'JP', 'Japan', 81, 'Japanese yen', '¥', 'JPY'),
( 'JO', 'Jordan', 962, 'Jordanian dinar', 'د.ا', 'JOD'),
( 'KZ', 'Kazakhstan', 7, 'Kazakhstani tenge', '₸', 'KZT'),
( 'KE', 'Kenya', 254, 'Kenyan shilling', 'Sh', 'KES'),
( 'KW', 'Kuwait', 965, 'Kuwaiti dinar', 'د.ك', 'KWD'),
( 'LB', 'Lebanon', 961, 'Lebanese pound', 'ل.ل', 'LBP'),
( 'MG', 'Madagascar', 261, 'Malagasy ariary', 'Ar', 'MGA'),
( 'MY', 'Malaysia', 60, 'Malaysian ringgit', 'RM', 'MYR'),
( 'MU', 'Mauritius', 230, 'Mauritian rupee', '₨', 'MUR'),
( 'MX', 'Mexico', 52, 'Mexican peso', '$', 'MXN'),
( 'MA', 'Morocco', 212, 'Moroccan dirham', 'د.م.', 'MAD'),
( 'MZ', 'Mozambique', 258, 'Mozambican metical', 'MT', 'MZN'),
( 'MM', 'Myanmar', 95, 'Burmese kyat', 'K', 'MMK'),
( 'NP', 'Nepal', 977, 'Nepalese rupee', '₨', 'NPR'),
( 'NZ', 'New Zealand', 64, 'New Zealand dollar', '$', 'NZD'),
( 'NI', 'Nicaragua', 505, 'Nicaraguan córdoba', 'C$', 'NIO'),
( 'NG', 'Nigeria', 234, 'Nigerian naira', '₦', 'NGN'),
( 'NO', 'Norway', 47, 'Norwegian krone', 'kr', 'NOK'),
( 'OM', 'Oman', 968, 'Omani rial', 'ر.ع.', 'OMR'),
( 'PK', 'Pakistan', 92, 'Pakistani rupee', '₨', 'PKR'),
( 'PA', 'Panama', 507, 'Panamanian balboa', 'B/.', 'PAB'),
( 'PY', 'Paraguay', 595, 'Paraguayan guaraní', '₲', 'PYG'),
( 'PE', 'Peru', 51, 'Peruvian nuevo sol', 'S/.', 'PEN'),
( 'PH', 'Philippines', 63, 'Philippine peso', '₱', 'PHP'),
( 'PL', 'Poland', 48, 'Polish złoty', 'zł', 'PLN'),
( 'PT', 'Portugal', 351, 'Euro', '€', 'EUR'),
( 'RO', 'Romania', 40, 'Romanian leu', 'lei', 'RON'),
( 'RU', 'Russia', 70, 'Russian ruble', '₽', 'RUB'),
( 'SA', 'Saudi Arabia', 966, 'Saudi riyal', 'ر.س', 'SAR'),
( 'SN', 'Senegal', 221, 'West African CFA fra', 'Fr', 'XOF'),
( 'SG', 'Singapore', 65, 'Singaporean dollar', 'S$', 'SGD'),
( 'SK', 'Slovakia', 421, 'Euro', '€', 'EUR'),
( 'ZA', 'South Africa', 27, 'South African rand', 'R', 'ZAR'),
( 'ES', 'Spain', 34, 'Euro', '€', 'EUR'),
( 'LK', 'Sri Lanka', 94, 'Sri Lankan rupee', 'Rs or රු', 'LKR'),
( 'SE', 'Sweden', 46, 'Swedish krona', 'kr', 'SEK'),
( 'CH', 'Switzerland', 41, 'Swiss franc', 'Fr', 'CHF'),
( 'KR', 'South Korea', 82, 'South Korean won', '₩', 'KWR'),
( 'TW', 'Taiwan', 886, 'New Taiwan dollar', '$', 'TWD'),
( 'TZ', 'Tanzania', 255, 'Tanzanian shilling', 'Sh', 'TZS'),
( 'TH', 'Thailand', 66, 'Thai baht', '฿', 'THB'),
( 'TN', 'Tunisia', 216, 'Tunisian dinar', 'د.ت', 'TND'),
( 'TR', 'Turkey', 90, 'Turkish lira', '₺', 'TRY'),
( 'UG', 'Uganda', 256, 'Ugandan shilling', 'Sh', 'UGX'),
( 'UA', 'Ukraine', 380, 'Ukrainian hryvnia', '₴', 'UAH'),
( 'AE', 'United Arab Emirates', 971, 'United Arab Emirates', 'د.إ', 'AED'),
( 'GB', 'United Kingdom', 44, 'British pound', '£', 'GBP'),
( 'US', 'United States', 1, 'United States dollar', '$', 'USD'),
( 'UY', 'Uruguay', 598, 'Uruguayan peso', '$', 'UYU'),
( 'UZ', 'Uzbekistan', 998, 'Uzbekistani som', "so'm", 'UZS'),
( 'VE', 'Venezuela', 58, 'Venezuelan bolívar', 'Bs F', 'VEF'),
( 'VN', 'Vietnam', 84, 'Vietnamese đồng', '₫', 'VND'),
( 'CI', "Côte d'Ivoire", 225, 'West African CFA franc', 'Fr', 'XOF'),
( 'PR', "Puerto Rico", 1, 'United States Dollar', '$', 'USD'),
( 'HK', "Hong Kong", 852, 'Hong Kong dollar', 'HK$', 'HKD'),
( 'NL', "Netherlands", 31, 'Euro', '€', 'EUR'),
( 'ZM', 'Zambia', 260, 'Zambian kwacha', 'ZK', 'ZMW'),
( 'ZW', 'Zimbabwe', 263, 'United States Dollar', '$', 'USD');